### PR TITLE
Automating process of setting up Ansible vars

### PR DESCRIPTION
**Pull request by trumant**

### CODE REVIEW

**Comment by conorsch** [comment]
Thanks for sharing! Validating the checksums against the remotely hosted list is definitely an improvement here, as is disposing of the VM for a successful build. 

If the regular expressions for validating the checksums don't match, the `rake` task errors out appropriately, and does not proceed to run Ansible. If the Ansible playbook encounters any errors (I introduced a few to check), the output is less than helpful:

```
$ bundle exec rake
Building packages
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
Packages built and now available in build/
```

However, the VM is preserved on error, and running `vagrant provision` will get you the full Ansible output again, complete with errors. After looking this over, I'm included to merge as-is, since the automation preserves the current workflow.

@garrettr, review?

**Comment by trumant** [comment]
@conorsch - Thanks for the testing and feedback. Let me submit a change to address the ansible error case you mention. That was definitely an oversight.

**Comment by conorsch** [comment]
@trumant Rad, thanks for adding the error message! Works as expected:

```
bundle exec rake
Building packages
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
Vagrant or Ansible playbook has failed.
Run
    vagrant status
and
    vagrant provision
to troubleshoot.
```

Now behold, as I put first one leg, then another, then my entire torso, into the mouth of this gift horse: `sed -i -e '28s/puts/fail/' Rakefile`

That is, change the `puts` to `fail` on line 26 of the Rakefile. Doing so will ensure that the `rake` task exits with a failed status, so chained commands (or future unimplemented tasks) are aborted when the error is reached. As long as the failed command exits with a non-zero code, I'm happy.

**Comment by trumant** [comment]
Indeed. A proper exit code is preferred.

**Pull request merged**
